### ISSUE TITLE
inference on one image /test

### ISSUE THREAD

**Issue by johndpope** [liuhyCV/single-image-depth-estimation#2]
I managed to download the 2gb file -> 
update the directories
re-create the training csv
run the training
python main.py

I want to run testing 

TRAIN = False
REFINE_TRAIN = False
FINE_TUNE = False

TEST = True
REFINE_TEST = False
TEST_SINGLE = True

these lines don't compile
#from dataset import DataSet
#from dataset import output_predict, output_predict_test, output_predict_test_single

NameError: global name 'DataSet' is not defined

output_predict, output_predict_test, output_predict_test_single

**Comment by liuhyCV** [comment]
sorry for disorder code. I have add dataset.py in root folder.

**Comment by johndpope** [comment]
Thank you so much

**Comment by johndpope** [comment]
I love the report. I want to do real time detection for linear and geometry as per your final slides. 
I wonder if this will help / they have a boundingbox detector / need a line / linear perspective detector. I'm sure this could be achieved given how close this work is.
https://github.com/tensorflow/models/tree/master/object_detection
