### ISSUE TITLE
Validation Logic

### ISSUE THREAD

**Issue by rvarun7777** [liuhyCV/single-image-depth-estimation#3]
Could you please tell me how you decided on the VAL_NUM to be 280? Is the validation logic correct?
And why the while loop used to validate and collect the total validation loss?

**Comment by liuhyCV** [comment]
set the val_num = 280 is just for convenience. It just calculate the average of 280 image iou

**Comment by rvarun7777** [comment]
Do you think this validation logic is correct? Different numbers will yield different validation results. So should we go in hand with the number of images trained per batch?

**Comment by liuhyCV** [comment]
It just calculate eval_num images, so the result is no problem and will not arisen Different numbers will yield different validation results
