### ISSUE TITLE
How to use task.py?

### ISSUE THREAD

**Issue by Somdyuti2** [liuhyCV/single-image-depth-estimation#4]
I ran main.py which is essentially train.py for the 100000 steps. However, the eval_predictions I am getting are not good and are almost the same for all images. Also, I do not see the option of fine tuning the network in train.py. All those options are in task.py.  So, I presume that task.py is the actual file that one should run in order to get the fine tuned model and reasonably good outputs. Please correct me if I am wrong here. 

While running task.py, I am unable to read the data; I think there is some mismatch between the train.csv and test.csv files that I am using and the ones needed for dataset.py (which is being called from task.py). Especially, I don't understand the following line

 ```
filename, depth_filename, depthMeters_filename = tf.decode_csv(serialized_example,
                                                                   [["img"], ["annotation"], ["meters"]])
```

what are "img", "annotation" and "meters" in the above line? Kindly clarify this. I have been trying to execute task.py, with the train.csv and test.csv as generated by your generate_csv_file.py, but I think the file reading operation is not successful as in this case, you seem to be reading in 3 fields whereas only 2 fields are there in the csv files generated by generate_csv_file.py. Consequently, the code crashes with an 
OutofRangeError in FIFO queue. Please provide the code required for the csv files for task.py or at least the correct format and explanation for running it.

**Comment by Somdyuti2** [comment]
I have figured it out. Had to modify generate_csv_file.py a little in order to create the proper csv files for task.py. Closing this.

**Comment by lijialei666** [comment]
Can you tell me how do you do it? Thank you!
